# 服务端口
server:
  port: 8081

#数据源 mysql 8.0.16
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL

  #邮件
  mail:
    host: smtp.163.com
    username: cchaoan@163.com
    password: ac221613 #这里是授权码
    default-encoding: UTF-8



#持久层 mybatis-plus-springboot
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #mybatis-plus.typeEnumsPackage=com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 字段验证策略
      field-strategy: NOT_NULL
      # 逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
  type-aliases-package: com.ac.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#线程池
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 300

