# 服务端口
server:
  port: 8080

#数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://192.168.0.106:3306/test_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false

#持久层 mybatis-springboot
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.ac.model
  mapper-locations: classpath:mapper/*.xml